# Site wide configuration

title: Travis Leleu
locale: en_US
description: Travis writes to think out loud and remember.
logo: travisleleu.png
search: false
url: https://travisleleu.com

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-twitter-plugin
  # - jekyll-feed

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

google_analytics: UA—36127504-1

# Site owner
owner:
  name: Travis Leleu
  avatar: travisleleu.png
  email: me@travisleleu.com
  disqus-shortname:
  twitter: #username
  facebook: #username
  github: #username
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: travisleleu
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
